server:
  port: 8080
  servlet:
    context-path: /api
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: katseliv2001
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db.migration.v1/changelog.yaml
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp